In [1]:
import numpy as np

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [4]:
DB=np.arange(1,20,2)

In [5]:
DB.ndim

1

In [6]:
a=np.array([[1,2,3],[4,5,6]])

In [7]:
a.ndim

2

In [8]:
a.shape

(2, 3)

In [9]:
b=np.array([[1,2,3],[4,5,6],[6,7,8]])

In [10]:
b.ndim

2

In [11]:
c=np.array([[[1,2,3],[5,6,7]],[[5,6,7],[8,9,0]]])

In [12]:
c.ndim

3

Comparision between list and numpy

In [13]:
L=[1,2,"Aadarsh",4,7.8]

In [14]:
L  # List is heterogeneous

[1, 2, 'Aadarsh', 4, 7.8]

In [15]:
c=np.array([1, 2, 'Aadarsh', 4, 7.8])

In [16]:
c

array(['1', '2', 'Aadarsh', '4', '7.8'], dtype='<U32')

In [17]:
type(c)

numpy.ndarray

In [20]:
print(c.dtype)
# Explanation: NumPy arrays are homogeneous. When mixed types are passed during array creation,
# NumPy attempts to find a common data type that can represent all elements. In this case,
# to accommodate the string 'Aadarsh', all other numeric elements (integers and float)
# were 'upcasted' or converted to strings. This ensures that the array remains homogeneous
# but with a different data type than just numbers. Hence, no error occurs, but the array's
# elements are all of type string (Unicode string, represented as '<U32' here).

<U32


Conversion of data type in numpy

In [21]:
import numpy as np

In [29]:
ds=np.arange(1,5)

In [30]:
ds

array([1, 2, 3, 4])

In [23]:
# convert to flot

In [31]:
ds.astype('float')

array([1., 2., 3., 4.])

In [34]:
ds.astype('str')

array(['1', '2', '3', '4'], dtype='<U21')

In [37]:
string1=np.array(['Aadarsh','Dhoni','kohli'])

In [38]:
string1.astype('int')

ValueError: invalid literal for int() with base 10: np.str_('Aadarsh')

The error ValueError: invalid literal for int() with base 10: np.str_('Aadarsh') occurs because you are trying to convert strings that are not numerical (like 'Aadarsh') into integers. The astype('int') method in NumPy can only convert strings to integers if the strings themselves represent valid numbers.

**Indexing and slicing**

In [43]:
num=np.array([5,6,7,8,93,4])

In [52]:
# indexing
num[5]

np.int64(4)

In [53]:
# to access multiple element

num[5,6] # error because num is 1-D and you are accessing like 2-D

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [54]:
num[[1,4]]  # here you are accessing correctly

array([ 6, 93])

In [55]:
# For 2-D array
num1=np.array([[2,3,4],[6,7,8],[4,6,7]])

In [56]:
num1.ndim

2

In [58]:
#to access the -> 8

num1[1,2]  # this meanse get the data from 1 index of 2 index value

np.int64(8)

In [60]:
num1[1]  # this will give list because at index 1 list is available

array([6, 7, 8])

In [61]:
# Slicing

num[1:4]  # this will slice value from index 1 to 3 because 4 is excluded

array([6, 7, 8])

In [63]:
# How do you slice 2-D

num1[[0:2],[0:3]]

SyntaxError: invalid syntax (ipython-input-97754530.py, line 3)

The SyntaxError: invalid syntax in your code is because of how you're trying to slice the 2-D NumPy array. Instead of using double square brackets around your slices like num1[[0:2],[0:3]], you should use single square brackets with a comma to separate the row and column slices, like num1[0:2, 0:3]. This correctly selects rows from index 0 up to (but not including) 2, and columns from index 0 up to (but not including) 3.

In [64]:
num1[0:3,0:2]

array([[2, 3],
       [6, 7],
       [4, 6]])

Comparision with value

In [70]:
num<6  #This will give true if value is less then 6 otherwise it will give false

array([ True, False, False, False, False,  True])

In [72]:
# if you want the value which is less the 6 -> use below

num[num<6]

array([5, 4])

In [75]:
num[num%2==0]

array([6, 8, 4])

Reshape

In [88]:
twoD=np.array([[2,3,4],[6,7,8],[1,2,3]])

In [89]:
twoD.ndim

2

In [90]:
# to Convert this into 1-D array use reshape

oneD=twoD.reshape(1,9)  # this will convert 1-D in 1-Row and 9 column

In [91]:
twoD

array([[2, 3, 4],
       [6, 7, 8],
       [1, 2, 3]])

In [92]:
oneD

array([[2, 3, 4, 6, 7, 8, 1, 2, 3]])

In [94]:
# now Convert oneD to 2-D

oneD.reshape(3,3)

array([[2, 3, 4],
       [6, 7, 8],
       [1, 2, 3]])

In [95]:
oneD.reshape(4,5)

ValueError: cannot reshape array of size 9 into shape (4,5)

The ValueError: cannot reshape array of size 9 into shape (4,5) means you're trying to change the array oneD (which has 9 elements) into a new shape that would require 20 elements (4 rows * 5 columns). For a reshape operation to be successful, the total number of elements in the original array must match the total number of elements in the new shape.
Therefore, whatever the shape we're trying to reshape to, must be able to incorporate the number of elements that we have.



In [97]:
oneD.reshape(9,-1) # It will convert to 9 row and it will set column accordingly

array([[2],
       [3],
       [4],
       [6],
       [7],
       [8],
       [1],
       [2],
       [3]])

In [99]:
oneD.reshape(8,-1)

ValueError: cannot reshape array of size 9 into shape (8,newaxis)

he ValueError: cannot reshape array of size 9 into shape (8,newaxis) occurs because the array oneD has 9 elements. You're trying to reshape it into 8 rows, but 9 is not perfectly divisible by 8. NumPy needs to maintain the same total number of elements when reshaping, and it cannot infer a whole number of columns if the total elements don't divide evenly by the specified row count.



In [103]:
oneD.reshape(-1, -1) # This will give error because you can only specify one unknown dimension

ValueError: can only specify one unknown dimension

In [105]:
len(oneD)

1

In [107]:
len(oneD[0])

9

In [110]:
a=np.arange(12).reshape(3,4)

In [111]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Transpose

In [113]:
a.T # this will transpose our 2-D array

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [115]:
print(a.T.ndim,a.T.shape)

2 (4, 3)


###How will you print the diagonal elements of the following 2D array?

In [116]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
# Create 4X4 matrix

In [118]:
b=np.arange(16).reshape(4,4)

In [138]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [147]:
b[[0,1,2,3],[0,1,2,3]]

array([ 0,  5, 10, 15])

In [148]:
b[[0],[1]]

array([1])