In [45]:
import numpy as np

In [46]:
#Shallow copy and deep copy

In [47]:
# we'll create numpy array

In [48]:
a=np.arange(4)

In [49]:
a

array([0, 1, 2, 3])

In [50]:
b=a.reshape(2,2)

In [51]:
b

array([[0, 1],
       [2, 3]])

In [52]:
a[0]=100

In [53]:
a

array([100,   1,   2,   3])

In [54]:
b

array([[100,   1],
       [  2,   3]])

In [55]:
# This above example is shallow copy

"""
  Numpy re-uses data as much as possible instead of dublicating it.
  This helps numpy to be efficient
  when we created b=a.reshape(2,2)
  -> Numpy did not make a copy of a to store b, as we clearly see
  -> It is using the same data as in a
  -> it just look different(reshaped) in b
  -> That is why, any changes in a automatically gets reflected in b
"""

'\n  Numpy re-uses data as much as possible instead of dublicating it.\n  This helps numpy to be efficient\n  when we created b=a.reshape(2,2) \n  -> Numpy did not make a copy of a to store b, as we clearly see\n  -> It is using the same data as in a\n  -> it just look different(reshaped) in b\n  -> That is why, any changes in a automatically gets reflected in b\n'

In [56]:
np.shares_memory(a, b) # Share memory

True

In [57]:
# Deep copy example

In [58]:
a=np.arange(4)

In [59]:
a

array([0, 1, 2, 3])

In [60]:
# Create c

In [61]:
c=a+2

In [62]:
c

array([2, 3, 4, 5])

In [63]:
a[0]=100

In [64]:
a

array([100,   1,   2,   3])

In [65]:
c

array([2, 3, 4, 5])

In [66]:
np.shares_memory(a,c)  # Does not share memory

False

In [67]:
# As we can see c did not get affected when we changing a
# Because it is an operation.
# A more permanent changes in data
# So numpy has to create a seprate copy for c i.e deep copy of array a for array c

In [68]:
# Permanent -> deep copy
# One time operation -> use same data for similer operation -> Shallow copy

In [69]:
# Note -> Shallow copy : Reshaping, slicing
#         Deep copy : Arthmetic operation and masking

In [70]:
"""
Shallow copy: We can create shallow copy by using view()
Deep copy: We can create deep copy by using copy()
"""

'\nShallow copy: We can create shallow copy by using view()\nDeep copy: We can create deep copy by using copy()\n'

In [71]:
a=np.arange(4)

In [72]:
b=a.view() # Creating shallow copy

In [73]:
b

array([0, 1, 2, 3])

In [75]:
a[0]=100

In [76]:
a

array([100,   1,   2,   3])

In [77]:
b

array([100,   1,   2,   3])

In [87]:
a=np.arange(4)

In [88]:
b=a.copy() # Creating deep copy

In [89]:
a

array([0, 1, 2, 3])

In [90]:
b

array([0, 1, 2, 3])

In [91]:
a[0]=100

In [92]:
a

array([100,   1,   2,   3])

In [93]:
b

array([0, 1, 2, 3])

Spliting

In [94]:
# np.split() -> Split array into multiple subarray

In [95]:
"""
it takes arguemnt as np.split(array, indices_or_sections, axis)
indices_or_sections -> int n -> the array will be divide n equal array along axis
if indices_or_sections is 1-D array sorted integers the entries indicate where along an axis the array should be split
if an index exceeds the dimension if array along axis, an empty subarray will be returned
"""
"""
"""

'\n'

In [96]:
a=np.arange(9)

In [97]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [98]:
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [99]:
np.split(a,4)

ValueError: array split does not result in an equal division

In [100]:
# Important requisite

# -> number of element in the array should be divisible by number of sections

In [101]:
b=np.arange(10)

In [102]:
np.split(b,3)

ValueError: array split does not result in an equal division

In [104]:
b[0:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [105]:
np.split(b[0:-1],3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [106]:
# Spliting on the basis of exact indices

In [107]:
c=np.arange(16)

In [108]:
np.split(c,[3,5,6])

[array([0, 1, 2]),
 array([3, 4]),
 array([5]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])]

In [109]:
# spliting an array into multiple array horizontally (column-wise)

In [114]:
x=np.arange(16.0).reshape(4,4) # Split array into subarray horizontally column wise

In [115]:
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [112]:
np.hsplit(x,2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [113]:
np.vsplit(x,2) # Split array into subarray verticallly row wise

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

Stacking

In [116]:
a=np.arange(1,5)

In [117]:
b=np.arange(2,6)

In [118]:
c=np.arange(3,7)

In [119]:
a

array([1, 2, 3, 4])

In [120]:
b

array([2, 3, 4, 5])

In [121]:
c

array([3, 4, 5, 6])

In [122]:
np.vstack([b,c,a])

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [1, 2, 3, 4]])

In [123]:
np.hstack([b,c,a])

array([2, 3, 4, 5, 3, 4, 5, 6, 1, 2, 3, 4])

Concatenate()

In [124]:
# Create a new array by appending arrays after each other. along a given axis

In [125]:
a=np.array([1,2,3])

In [127]:
b=np.array([[1,2,3],[4,5,6]])

In [128]:
np.concatenate([a,b],axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [129]:
# concatenate only work if both a and b having same dimension

In [130]:
a=np.array([[1,2,3]])

In [132]:
a.ndim

2

In [133]:
b.ndim

2

In [134]:
np.concatenate([a,b],axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [135]:
np.concatenate([a,b],axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2

In [136]:
c=np.array([[1,2,3],[4,5,6]])

In [137]:
d=np.array([[1,2,3],[4,5,6]])

In [138]:
np.concatenate([c,d],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])