In [7]:
import numpy as np

Sorting ->

Syntax-> np.sort(arr) return a sorted copy of an array
It is sorting in assending order

In [8]:
a=np.array([1,2,3,4,5,6,74,5,6])

In [9]:
a

array([ 1,  2,  3,  4,  5,  6, 74,  5,  6])

In [10]:
b=np.sort(a) #Sorting done in assending order

In [11]:
b

array([ 1,  2,  3,  4,  5,  5,  6,  6, 74])

In [12]:
# If we want to do sorting in descending order then how can we do it?

c=np.array([4,6,7,1,2,3,9,8,7])

In [13]:
c

array([4, 6, 7, 1, 2, 3, 9, 8, 7])

In [14]:
D=np.sort(c)

In [15]:
D[::-1]

array([9, 8, 7, 7, 6, 4, 3, 2, 1])

In [16]:
#Sorting in 2-D array

In [17]:
A2=np.array([[1,5,3],[2,5,7],[400,200,300]])

In [18]:
A2

array([[  1,   5,   3],
       [  2,   5,   7],
       [400, 200, 300]])

In [19]:
np.sort(A2,axis=1) #Row wise sorting

array([[  1,   3,   5],
       [  2,   5,   7],
       [200, 300, 400]])

In [20]:
A3=np.array([[1,5,3],[600,5,7],[400,200,300]])

In [21]:
A3

array([[  1,   5,   3],
       [600,   5,   7],
       [400, 200, 300]])

In [22]:
np.sort(A3,axis=0) # column wise sorting

array([[  1,   5,   3],
       [400,   5,   7],
       [600, 200, 300]])

Element wise multiplication

In [23]:
a=np.arange(1,6)

In [24]:
a

array([1, 2, 3, 4, 5])

In [25]:
a*5

array([ 5, 10, 15, 20, 25])

In [26]:
b=np.arange(6,11)

In [27]:
b*5

array([30, 35, 40, 45, 50])

In [28]:
a*b

array([ 6, 14, 24, 36, 50])

In [29]:
c=np.array([2,3,5])

In [30]:
a*c  #Error : Both array should have in same size

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [ ]:
e=np.arange(12).reshape(3,4)

In [ ]:
f=np.arange(13,25).reshape(3,4)

In [ ]:
e

In [ ]:
f

In [ ]:
e*f

In [ ]:
#Takeaway:

#-> Array*Number=> works
#-> Array*Array(same shape) => works
#-> Array*Array(different shape) => Does not work

Matrix multiplication

-> Number of column of the first matrix shoud be equal to number of  rows of the second matrix

In [ ]:
# (A,B)*(B,C) -> (A,C)
# (3,4)*(4,3) -> (3,3)

In [ ]:
a=np.arange(12).reshape(3,4)

In [ ]:
b=np.arange(13,25).reshape(4,3)

In [ ]:
a.shape, b.shape

In [ ]:
#For matrix multiplication
# 1-> we use np.dot

In [ ]:
np.dot(a,b)

In [ ]:
# 2-> we use np.matmul

In [ ]:
np.matmul(a,b)

In [31]:
# 3-> we use a@b

In [32]:
a@b

np.int64(130)

In [33]:
a@5 # This will not work

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
np.matmul(a,5) #This will not work

In [ ]:
np.dot(a,5) #This will work -> dot product work one element wise operation

In [34]:
"""
 important point
 1. dot() function supports vector multiplication with scaler value, which is not possible with matmul()
 2.  Vector * vector will work for matmul() but vector * scaler won't work.

"""

"\n important point \n 1. dot() function supports vector multiplication with scaler value, which is not possible with matmul()\n 2.  Vector * vector will work for matmul() but vector * scaler won't work.\n\n"

Vectorization

In [35]:
""" vectorization in numpy array refer to performing operation on entire arrays
or array elements simultaneously,which is significatly faster and more efficient
then using explicit loop"""

' vectorization in numpy array refer to performing operation on entire arrays \nor array elements simultaneously,which is significatly faster and more efficient \nthen using explicit loop'

In [36]:
a=np.arange(10)

In [37]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
"""
 -> 1D array : Vector
 -> 2D array : Matrix
 -> 3D array : Tensor

"""

'\n -> 1D array : Vector\n -> 2D array : Matrix\n -> 3D array : Tensor\n\n'

In [39]:
def random_operation(x):
  if x%2==0:
    x+=2
  else:
    x-=2
  return x

In [40]:
random_operation(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [44]:
b=np.array([2,3,4,5,6,7])  # This is basic solution by using loop
#b=[2,3,4,5,6,7]

In [45]:
def random_operation(x):
  L=[]
  #E=None
  for i in x:
      if i%2==0:
        i+=2
        L.append(i)
      else:
        i-=2
        L.append(i)
  return L

In [46]:
random_operation(b)

[np.int64(4), np.int64(1), np.int64(6), np.int64(3), np.int64(8), np.int64(5)]

In [47]:
cool_operaion=np.vectorize(random_operation)

In [48]:
type(cool_operaion)

numpy.vectorize

In [49]:
C=np.array([2,3,4,5,6,7])

In [50]:
def random_operation(x):
  if x%2==0:
    x+=2
  else:
    x-=2
  return x

In [51]:
cal_vec=np.vectorize(random_operation)


In [52]:
cal_vec(C)

array([4, 1, 6, 3, 8, 5])

Broadcasting

In [53]:
  """
 Brodcasting in numpy is the automatic and implicit extension of array dimension to enable element wise
 operations between arrays with different shapes.
 """

'\n Brodcasting in numpy is the automatic and implicit extension of array dimension to enable element wise \n operations between arrays with different shapes.\n '

Case-1

In [61]:
a=np.tile(np.arange(0,40,10), (3,1))  # tile is used when you want to replicate an array in a grid-like pattern without writing loops.

In [62]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [63]:
a=a.T

In [64]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [65]:
b=np.tile(np.arange(0,3), (4,1))

In [66]:
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [67]:
a.shape, b.shape

((4, 3), (4, 3))

In [70]:
a+b  # if both shape are same no need to broadcaste

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [71]:
a*b

array([[ 0,  0,  0],
       [ 0, 10, 20],
       [ 0, 20, 40],
       [ 0, 30, 60]])

Case -2

In [72]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [74]:
c=np.array([0,1,2])

In [75]:
c

array([0, 1, 2])

In [76]:
a.shape,c.shape

((4, 3), (3,))

In [78]:
a+c

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [80]:
# C was broadcasting along rows (Vertically)
# So that a and c can be made compatible

Case-3

In [81]:
d=np.array([0,10,20,30]).reshape(4,1)

In [82]:
d

array([[ 0],
       [10],
       [20],
       [30]])

In [84]:
c

array([0, 1, 2])

In [85]:
d.shape, c.shape

((4, 1), (3,))

In [86]:
d+c

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [89]:
"""
d was broadcaste along columns (Horizontally) So that a and c can be made compatible.
c was broadcasted along rows (Vertically) So that a and c can be made compatible.
"""

'\nd was broadcaste along columns (Horizontally) So that a and c can be made compatible.\nc was broadcasted along rows (Vertically) So that a and c can be made compatible.\n'

In [90]:
a=np.arange(8).reshape(2,4)

In [92]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [93]:
b=np.arange(16).reshape(4,4)

In [94]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [104]:
a.shape,b.shape

((2, 4), (4, 4))

In [105]:
a+b

ValueError: operands could not be broadcast together with shapes (2,4) (4,4) 

In [99]:
# A+A (same shape) -> Works
# A+A (1D) -> works
# A+number-> Works
# A+A(different shape but still 2D) -> Does not word

### Scenario 1: Mismatched Dimensions (Revisiting `a+b` from the notebook)

In [101]:
import numpy as np

a = np.arange(8).reshape(2, 4)
b = np.arange(16).reshape(4, 4)

print(f"Shape of a: {a.shape}")
print(f"Shape of b: {b.shape}")

try:
    result = a + b
    print(result)
except ValueError as e:
    print(f"Error: {e}")

Shape of a: (2, 4)
Shape of b: (4, 4)
Error: operands could not be broadcast together with shapes (2,4) (4,4) 


In [106]:
A=np.arange(1,10).reshape(3,3)

In [107]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
B=np.array([-1,0,1])

In [109]:
A.shape, B.shape

((3, 3), (3,))

In [111]:
A+B

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [112]:
A=np.arange(12).reshape(3,4)

In [113]:
B=np.array([1,2,3])

In [114]:
A.shape, B.shape

((3, 4), (3,))

In [115]:
A+b

ValueError: operands could not be broadcast together with shapes (3,4) (4,4) 