In [ ]:
A=np.array([[6,6,4,7,9],
 [0,2,2,9,3],
 [6,0,2,5,2],
 [2,4,3,5,5]])


In [ ]:
B=np.array([[6,6,4,7,9],
 [0,2,2,9,3],
 [6,0,2,5,2],
 [2,4,3,5,5]])

In [ ]:
import numpy as np
np.matmul(A,B.T)

array([[218, 110,  97, 128],
       [110,  98,  55,  74],
       [ 97,  55,  69,  53],
       [128,  74,  53,  79]])

In [ ]:
Hsplit=np.hsplit(A,2)

ValueError: array split does not result in an equal division

In [ ]:
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])

In [ ]:
data=np.array([[100, 110, 120], [10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [ ]:
Vsplit=np.vsplit(data,4)

In [ ]:
Vsplit

[array([[100, 110, 120]]),
 array([[10, 20, 30]]),
 array([[40, 50, 60]]),
 array([[70, 80, 90]])]

In [ ]:
np.stack((Vsplit[0],Vsplit[1]),axis=1)

array([[[100, 110, 120],
        [ 10,  20,  30]]])

In [ ]:
np.concatenate((Vsplit[1],Vsplit[0]),axis=0)

array([[ 70,  80,  90],
       [100, 110, 120],
       [ 10,  20,  30],
       [ 40,  50,  60]])

In [ ]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(np.hstack((arr, arr[:, [0]])).shape)

(3, 4)


In [ ]:
!gdown https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd

Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /content/fit.txt
100% 3.43k/3.43k [00:00<00:00, 14.8MB/s]


In [ ]:
data = np.loadtxt('/content/fit.txt', dtype='str')
data

/tmp/ipython-input-3723169913.py:1: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  data = np.loadtxt('/content/fit.txt', dtype='str')


array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [ ]:
dataT=data.T

In [ ]:
dataT

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [ ]:
Active=dataT[5]

In [ ]:
np.unique(Active)

array(['Active', 'Inactive'], dtype='<U10')

In [ ]:
step_count=dataT[3]

In [ ]:
step_count[data[:,5]=='Active']

array(['223', '150', '150', '17', '193', '19', '101', '139', '164', '137',
       '22', '17', '9', '17', '32', '35', '220', '116', '23', '44', '131',
       '86', '194', '60', '121', '93', '53', '227', '125', '243', '14',
       '39', '158', '7', '213', '116', '180', '138', '176', '99', '0',
       '0'], dtype='<U10')

In [ ]:
step_count = step_count[data[:,5]=='Active']
np.mean(step_count,dtype='int')

IndexError: boolean index did not match indexed array along axis 0; size of axis is 42 but size of corresponding boolean axis is 96